 <link rel="stylesheet" href="{{asset('assets/texteditor/css/froala_editor.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/froala_style.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/code_view.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/colors.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/emoticons.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/image_manager.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/image.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/line_breaker.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/table.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/char_counter.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/video.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/fullscreen.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/file.css')}}">
  <link rel="stylesheet" href="{{asset('assets/texteditor/css/plugins/quick_insert.css')}}">